### ISSUE TITLE
Cldr.Calendar.Coptic.months_in_year/1

### ISSUE THREAD

**Issue by NickNeck** [elixir-cldr/cldr_calendars_coptic#1]
Hello,

the function `Cldr.Calendar.Coptic.months_in_year` is delegated to `Calendar.ISO`, but should this function not return `@months_in_year 13`.

Best regards
Marcus

**Comment by kipcole9** [comment]
You are quite correct and I really appreciate the bug report. Published [ex_cldr_calendars_coptic version 0.2.0](https://hex.pm/packages/ex_cldr_calendars_coptic/0.2.0). Changelog entry is:

### Bug Fixes

* Fix `Cldr.Calendar.Coptic.months_in_year/1`. Thanks to @NickNeck. Fixes #1

* Fix parsing for the `~D` sigil
